name: DEVELOP
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, vistelarte]
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Create env file
      run: |
        touch .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo HOST=${{ secrets.HOST }} >> .env
        cat .env
        
    - run: npm ci
    - run: npm run develop
